### ISSUE TITLE
Add manual of the helium levelmeter to the wiki

### ISSUE THREAD

**Issue by lindnerju** [SampleEnvironment/LHe-Level-Meter#3]
Hello, my name is Julian and I am working at the HZB (Berlin) in the department sample environment. One of my tasks is writing a manual of the helium levelmeter. Klaus K. proposed to add the content of this document to the Wiki of this repository. However, I am unable to open or to edit the Wiki section yet. Could you activate the Wiki or allow me to edit it? Or do you have a better idea for this? Kind regards, Julian.

**Comment by EddyLB** [comment]
Hi @lindnerju 
I answered in the Discussions section of the HZB team.
Cheers
